### ISSUE TITLE
selenium_download postinstall task breaks my widget

### ISSUE THREAD

**Issue by drushbrook** [watson-virtual-agents/chat-widget#142]
According to https://www.npmjs.com/package/@watson-virtual-agent/chat-widget selenium_download is not a dependancy. It is part of the postinstall process hence it breaks my upgrade process.  I will temporarily add selenium to the dependancies for my npm module but I believe it should either be added to the dependancies for the chat-widget or removed from the npm postinstall process.  

```
mini-dmacpro:wva_app daniel$ npm update

> @watson-virtual-agent/chat-widget@1.2.11 postinstall /Users/daniel/src/watson/client/xyz/dev/wva_app/node_modules/@watson-virtual-agent/chat-widget
> node ./test/selenium/download.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'selenium-download'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/daniel/src/watson/client/xyz/dev/wva_app/node_modules/@watson-virtual-agent/chat-widget/test/selenium/download.js:15:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.5.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! @watson-virtual-agent/chat-widget@1.2.11 postinstall: `node ./test/selenium/download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @watson-virtual-agent/chat-widget@1.2.11 postinstall script 'node ./test/selenium/download.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @watson-virtual-agent/chat-widget package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./test/selenium/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @watson-virtual-agent/chat-widget
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @watson-virtual-agent/chat-widget
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniel/src/watson/client/xyz/dev/wva_app/npm-debug.log
```

**Comment by ethanwinters** [comment]
Agreed, our next release (Wednesday) already has it moved to be run before the selenium tests instead of as a postinstall script.

**Comment by drushbrook** [comment]
Thanks for the update.
